name: Super-Linter and Auto-Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopend

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    name: Auto-Merge Pull Request
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Check if Super-Linter checks passed
        id: checks
        run: |
          if [ "$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/check-runs" | jq -r '.check_runs[] | select(.app.slug == "github/super-linter").conclusion')" == "success" ]; then
            echo "Super-Linter checks passed.";
            echo "::set-output name=checks_passed::true";
          else
            echo "Super-Linter checks failed or not completed.";
            echo "::set-output name=checks_passed::false";
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}

      - name: Merge Pull Request
        if: steps.checks.outputs.checks_passed == 'true'
        run: |
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"merge_method": "merge"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${PULL_REQUEST}/merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
